[2024-08-09T08:51:45.659+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T08:51:45.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_hongheo manual__2024-08-09T08:51:11.426878+00:00 [queued]>
[2024-08-09T08:51:45.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_hongheo manual__2024-08-09T08:51:11.426878+00:00 [queued]>
[2024-08-09T08:51:45.758+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-09T08:51:45.811+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gold_hongheo> on 2024-08-09 08:51:11.426878+00:00
[2024-08-09T08:51:45.816+0000] {standard_task_runner.py:63} INFO - Started process 3735 to run task
[2024-08-09T08:51:45.821+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Data_Warehouse', 'gold_hongheo', 'manual__2024-08-09T08:51:11.426878+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/etl_ldtbxh.dag.py', '--cfg-path', '/tmp/tmpyddzqegv']
[2024-08-09T08:51:45.823+0000] {standard_task_runner.py:91} INFO - Job 412: Subtask gold_hongheo
[2024-08-09T08:51:45.941+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Data_Warehouse.gold_hongheo manual__2024-08-09T08:51:11.426878+00:00 [running]> on host 45f7764b2bf2
[2024-08-09T08:51:46.146+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Data_Warehouse' AIRFLOW_CTX_TASK_ID='gold_hongheo' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T08:51:11.426878+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T08:51:11.426878+00:00'
[2024-08-09T08:51:46.147+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T08:51:53.793+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T08:51:53.794+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/gold/hongheo_gold.py", line 40, in run_gold_hongheo
    .load()
     ^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 314, in load
    return self._df(self._jreader.load())
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: requirement failed: The driver could not open a JDBC connection. Check the URL: None:None/LdtbxhStage
[2024-08-09T08:51:53.830+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Data_Warehouse, task_id=gold_hongheo, run_id=manual__2024-08-09T08:51:11.426878+00:00, execution_date=20240809T085111, start_date=20240809T085145, end_date=20240809T085153
[2024-08-09T08:51:53.879+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 412 for task gold_hongheo (requirement failed: The driver could not open a JDBC connection. Check the URL: None:None/LdtbxhStage; 3735)
[2024-08-09T08:51:53.900+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-09T08:51:53.942+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T08:51:53.977+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
