[2024-08-01T04:36:47.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T04:36:47.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.python_job manual__2024-08-01T04:36:36.194656+00:00 [queued]>
[2024-08-01T04:36:47.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.python_job manual__2024-08-01T04:36:36.194656+00:00 [queued]>
[2024-08-01T04:36:47.720+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-01T04:36:47.759+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-08-01 04:36:36.194656+00:00
[2024-08-01T04:36:47.771+0000] {standard_task_runner.py:63} INFO - Started process 67 to run task
[2024-08-01T04:36:47.777+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'python_job', 'manual__2024-08-01T04:36:36.194656+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmpuozcis9r']
[2024-08-01T04:36:47.779+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask python_job
[2024-08-01T04:36:47.852+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag.python_job manual__2024-08-01T04:36:36.194656+00:00 [running]> on host 24fc876e8f70
[2024-08-01T04:36:47.989+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T04:36:36.194656+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T04:36:36.194656+00:00'
[2024-08-01T04:36:47.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T04:36:48.023+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-01T04:36:48.026+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default jobs/word_count.py
[2024-08-01T04:36:51.332+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-01T04:36:51.334+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-08-01T04:36:51.336+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-08-01T04:36:51.336+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-08-01T04:36:51.337+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-08-01T04:36:51.338+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-08-01T04:36:51.338+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-08-01T04:36:51.339+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-08-01T04:36:51.339+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-08-01T04:36:51.340+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-08-01T04:36:51.341+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-01T04:36:51.356+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T04:36:51.372+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default jobs/word_count.py. Error code is: 1.
[2024-08-01T04:36:51.380+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_dag, task_id=python_job, run_id=manual__2024-08-01T04:36:36.194656+00:00, execution_date=20240801T043636, start_date=20240801T043647, end_date=20240801T043651
[2024-08-01T04:36:51.413+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default jobs/word_count.py. Error code is: 1.; 67)
[2024-08-01T04:36:51.437+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-01T04:36:51.502+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T04:36:51.524+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
