[2024-08-09T15:14:20.007+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T15:14:20.045+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_hongheo manual__2024-08-09T15:13:45.046007+00:00 [queued]>
[2024-08-09T15:14:20.064+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Data_Warehouse.gold_hongheo manual__2024-08-09T15:13:45.046007+00:00 [queued]>
[2024-08-09T15:14:20.065+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-09T15:14:20.101+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gold_hongheo> on 2024-08-09 15:13:45.046007+00:00
[2024-08-09T15:14:20.107+0000] {standard_task_runner.py:63} INFO - Started process 1530 to run task
[2024-08-09T15:14:20.112+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Data_Warehouse', 'gold_hongheo', 'manual__2024-08-09T15:13:45.046007+00:00', '--job-id', '531', '--raw', '--subdir', 'DAGS_FOLDER/etl_ldtbxh.dag.py', '--cfg-path', '/tmp/tmp1m09qb1e']
[2024-08-09T15:14:20.114+0000] {standard_task_runner.py:91} INFO - Job 531: Subtask gold_hongheo
[2024-08-09T15:14:20.206+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Data_Warehouse.gold_hongheo manual__2024-08-09T15:13:45.046007+00:00 [running]> on host 45f7764b2bf2
[2024-08-09T15:14:20.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Data_Warehouse' AIRFLOW_CTX_TASK_ID='gold_hongheo' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T15:13:45.046007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T15:13:45.046007+00:00'
[2024-08-09T15:14:20.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T15:14:34.216+0000] {logging_mixin.py:188} INFO - ====================
[2024-08-09T15:14:41.058+0000] {logging_mixin.py:188} INFO - +--------------------+----+-------------+-------------+-----------+----------+--------------------+--------------------+--------------------+----------+-------+--------+--------+-------+-------+------------+
|           family_id|year|province_name|district_name|family_code|owner_name|        hard_reasons|        get_policies|       need_policies|member_num|a_grade|b1_grade|b2_grade|b1_diff|b2_diff|final_result|
+--------------------+----+-------------+-------------+-----------+----------+--------------------+--------------------+--------------------+----------+-------+--------+--------+-------+-------+------------+
|966a5c75-d6f5-48c...|2022|     Đắk Nông|       Cư Jút|       7009|      NULL|[không có đất sản...|[hỗ trợ y tế, hỗ ...|[hỗ trợ nước sạch...|      NULL|   true|      45|      65|   NULL|   NULL|    hộ nghèo|
|f4773df9-32bc-417...|2023|     Đắk Nông|       Cư Jút|       7003|  Độ A Đạt|[không có đất sản...|[hỗ trợ y tế, hỗ ...|[hỗ trợ nước sạch...|         1|   true|      30|      58|   NULL|   NULL|    hộ nghèo|
|70321aa9-91b9-465...|2023|     Đắk Nông|       Cư Jút|       7009|Phùng A Sử|[không có đất sản...|[hỗ trợ y tế, hỗ ...|[hỗ trợ nước sạch...|         2|   true|      50|      32|      5|    -33|    hộ nghèo|
+--------------------+----+-------------+-------------+-----------+----------+--------------------+--------------------+--------------------+----------+-------+--------+--------+-------+-------+------------+
[2024-08-09T15:14:41.059+0000] {logging_mixin.py:188} INFO - None
[2024-08-09T15:14:41.059+0000] {logging_mixin.py:188} INFO - ====================
[2024-08-09T15:14:42.198+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T15:14:42.200+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/medallion/hongheo/gold.py", line 70, in run_gold_hongheo
    cur.execute(f"""UPDATE public."stgPovertyStatusFact"
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3:                                     member_num=None,
                                                       ^

[2024-08-09T15:14:42.223+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Data_Warehouse, task_id=gold_hongheo, run_id=manual__2024-08-09T15:13:45.046007+00:00, execution_date=20240809T151345, start_date=20240809T151420, end_date=20240809T151442
[2024-08-09T15:14:42.273+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 531 for task gold_hongheo (column "none" does not exist
LINE 3:                                     member_num=None,
                                                       ^
; 1530)
[2024-08-09T15:14:42.290+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-09T15:14:42.367+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T15:14:42.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
