[2024-08-07T08:18:59.711+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T08:18:59.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T08:18:40.474458+00:00 [queued]>
[2024-08-07T08:18:59.763+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T08:18:40.474458+00:00 [queued]>
[2024-08-07T08:18:59.764+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T08:18:59.805+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): bronze_time> on 2024-08-07 08:18:40.474458+00:00
[2024-08-07T08:18:59.811+0000] {standard_task_runner.py:63} INFO - Started process 5126 to run task
[2024-08-07T08:18:59.814+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Integrate_Time_Location_Dimension', 'bronze_time', 'manual__2024-08-07T08:18:40.474458+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/etl_time_location.dag.py', '--cfg-path', '/tmp/tmpzpurv8ru']
[2024-08-07T08:18:59.817+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask bronze_time
[2024-08-07T08:18:59.906+0000] {task_command.py:426} INFO - Running <TaskInstance: Integrate_Time_Location_Dimension.bronze_time manual__2024-08-07T08:18:40.474458+00:00 [running]> on host 45f7764b2bf2
[2024-08-07T08:19:00.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Integrate_Time_Location_Dimension' AIRFLOW_CTX_TASK_ID='bronze_time' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T08:18:40.474458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T08:18:40.474458+00:00'
[2024-08-07T08:19:00.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T08:19:00.764+0000] {logging_mixin.py:188} INFO - ==========================
[2024-08-07T08:19:00.772+0000] {logging_mixin.py:188} INFO - Index(['date_key', 'full_date', 'day_of_week', 'day_num_in_month',
       'day_num_overall', 'day_name', 'day_abbrev', 'weekday_flag',
       'week_num_in_year', 'week_num_overall', 'week_begin_date',
       'week_begin_date_key', 'month', 'month_num_overall', 'month_name',
       'month_abbrev', 'quarter', 'year', 'yearmo', 'fiscal_month',
       'fiscal_quarter', 'fiscal_year', 'last_day_in_month_flag',
       'same_day_year_ago_date'],
      dtype='object')
[2024-08-07T08:19:00.810+0000] {logging_mixin.py:188} INFO -    date_key  full_date  ...  last_day_in_month_flag  same_day_year_ago_date
0  20200101 2020-01-01  ...           Not Month End              2019-01-01
1  20200102 2020-01-02  ...           Not Month End              2019-01-02
2  20200103 2020-01-03  ...           Not Month End              2019-01-03
3  20200104 2020-01-04  ...           Not Month End              2019-01-04
4  20200105 2020-01-05  ...           Not Month End              2019-01-05

[5 rows x 24 columns]
[2024-08-07T08:19:00.810+0000] {logging_mixin.py:188} INFO - ==========================
[2024-08-07T08:19:00.832+0000] {logging_mixin.py:188} INFO - start to insert...
[2024-08-07T08:19:00.849+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T08:19:00.850+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/timelocation/load_date.py", line 29, in readTimeExcel
    cur.execute(f'''INSERT INTO "stgDate"({cols}) VALUES {tuple(row)}''')
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "stgDate_pkey"
DETAIL:  Key (date_key)=(20200101) already exists.

[2024-08-07T08:19:00.866+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Integrate_Time_Location_Dimension, task_id=bronze_time, run_id=manual__2024-08-07T08:18:40.474458+00:00, execution_date=20240807T081840, start_date=20240807T081859, end_date=20240807T081900
[2024-08-07T08:19:00.902+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 203 for task bronze_time (duplicate key value violates unique constraint "stgDate_pkey"
DETAIL:  Key (date_key)=(20200101) already exists.
; 5126)
[2024-08-07T08:19:00.914+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-07T08:19:00.951+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T08:19:00.976+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
